### ISSUE TITLE
Install package on Symfony 5.1

### ISSUE THREAD

**Issue by aniskasmi** [Cethy/GooglePlaceAutocompleteBundle#12]
Hi 

I have problem to install our package on Symfony 5.1 

When i composer require 

> Problem 1
>     - Root composer.json requires cethyworks/google-place-autocomplete-bundle ^5.1 -> satisfiable by cethyworks/google-place-autocomplete-bundle[v5.1].
>     - cethyworks/google-place-autocomplete-bundle v5.1 requires twig/twig ^1.0||^2.0|^5.0 -> found twig/twig[1.3.0, ..., v1.44.1, v2.0.0, ..., v2.14.1] but the package is fixed to v3.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.`

This error message is return

I test to put directly on composer.json and 

> HTTP 500 Internal Server Error
> Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /vagrant/source/public/AzAgency/vendor/cethyworks/google-place-autocomplete-bundle/src/DependencyInjection/Configuration.php on line 20 and at least 1 expected

This error is return 

Thx

**Comment by aniskasmi** [comment]
@Cethy If you have solution thx a lot

**Comment by Cethy** [comment]
@skPink I'm sorry, the package is not maintained anymore (I switch to full javascript, to never going back to php).
That said, i think the problem comes from a breaking change in Symfony (4 or 5) in the TreeBuilder constructor :
According to https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Config/Definition/Builder/TreeBuilder.php, the TreeBuilder needs the name of the package directly into the constructor and not in a ->root() method like it's done in this package. Looks like an easy fix ?

**Comment by aniskasmi** [comment]
@Cethy I test to fix this on PR #13

**Comment by aniskasmi** [comment]
@Cethy Any news ?

**Comment by Cethy** [comment]
I'm really sorry. I reviewed your PR but didn't publish it ...
